### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by dylanmcdiarmid**
I've been working with people in the virtualdom room on IRC to create some documentation for people interested in working with virtual-dom directly. If you want to read them online, I've tagged the release at https://github.com/littleloops/virtual-dom-docs-wip/tree/0.1 

Although the docs cover things in both vtree and vdom, @neonstalwart recommended vtree as the place to keep the documentation. Let me know your thoughts on this, and if you find any problems in the docs.

### CODE REVIEW

**Comment by dylanmcdiarmid** [comment]
Oops, linked to an incomplete release. I forgot to commit the README overview. Here's a new link https://github.com/littleloops/virtual-dom-docs-wip/tree/0.2

**Comment by Raynos** [comment]
You should feel encouraged to use `h()` in your examples where it makes sense.

**Comment by dylanmcdiarmid** [comment]
One of the reasons I didn't use the virtual-hyperscript syntax was that I considered it another project. Is this the case, or will it be officially part of the new merged virtual-dom? 

I also was thinking of people who may be reading docs at this low of a level because they want to write their own template language. Using virtual-hyperscript "officially" might make it seem like it would be the only supported option (even though at this point, it is the only option to my knowledge).

**Comment by Matt-Esch** [comment]
> One of the reasons I didn't use the virtual-hyperscript syntax was that I considered it another project. Is this the case, or will it be officially part of the new merged virtual-dom?

It is part of the new merged virtual-dom

> I also was thinking of people who may be reading docs at this low of a level because they want to write their own template language. Using virtual-hyperscript "officially" might make it seem like it would be the only supported option (even though at this point, it is the only option to my knowledge).

My preference is to keep the individual modules reserved for documentation for that module alone, and use the virtual-dom and mercury projects for higher level documentation.

**Comment by gsf** [comment]
Why keep documentation for parts of virtual-dom in separate repos if the code has been merged into one?

**Comment by Raynos** [comment]
Good question. I presume the documentation for everything will go into Matt-Esch/virtual-dom

**Comment by dylanmcdiarmid** [comment]
This PR was from before the merge. I'll close it for now, and try and get some changes in and resubmit to virtual-dom this week.

**Comment by neonstalwart** [comment]
did this ever make it into virtual-dom?

**Comment by dylanmcdiarmid** [comment]
Hey @neonstalwart, I had to concentrate on non-frontend related dev for a while, but I'll be moving back into virtual-dom/mercury development again this upcoming week, which should give me a chance to do the updates I need to the docs (Raynos asked for some examples to be moved from to virtual-hyperscript now that it's officially part of the project) and resubmit them to the merged virtual-dom. I'll pop into IRC as well this weekend and say hi.

**Comment by neonstalwart** [comment]
cool.  just wanted to make sure we didn't forget these docs - i think they're really valuable.

**Pull request closed without merging**
